server:
  port: 8089

spring:
  application:
    name: service-voiture
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Micro_VoitureDB?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: ${SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED:true}
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-interval: 10s

client:
  service:
    url: ${CLIENT_SERVICE_URL:http://localhost:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
