server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: ${SPRING_CLOUD_CONSUL_DISCOVERY_ENABLED:true}
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-interval: 10s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
